routes/admin.php
<?php


Auth::routes();

Route::get('/', 'HomeController@index')->name('dashboard');
Route::get('/home', 'HomeController@index')->name('dashboard');
Route::get('/dashboard', 'HomeController@index')->name('dashboard');
Route::get('about', 'HomeController@index');

Route::resource('roles', 'RoleController');

Route::resource('modules', 'ModuleController');

Route::get('/module/step1/{id?}', 'ModuleController@getStep1')->name('modules.create');
Route::get('/module/step2/{tablename?}', 'ModuleController@getStep2')->name('modules.create');
Route::get('/getJoinFields/{tablename?}', 'ModuleController@getJoinFields');
Route::get('/module/step3/{tablename?}', 'ModuleController@getStep3')->name('modules.create');

Route::post('/step1', 'ModuleController@postStep1');
Route::post('/step2', 'ModuleController@postStep2');
Route::post('/step3', 'ModuleController@postStep3');


Route::resource('users', 'UserController');

Route::resource('permissions', 'PermissionController');

//Route::resource('profile', 'UserController');

Route::get('user/profile', 'UserController@profile')->name('users.profile');
//Route::patch('users/profile-update/{id}', 'UserController@profileUpdate')->name('users.profile-update');

Route::resource('languages', 'LanguageController');

Route::resource('pages', 'PageController');

Route::resource('contactus', 'ContactUsController');

Route::resource('notifications', 'NotificationController');

Route::resource('menus', 'MenuController');

//Menu #TODO need to be fixed
Route::get('statusChange/{id}', 'MenuController@statusChange');

Route::post('updateChannelPosition', 'MenuController@update_channel_position')->name('channels');
Route::resource('settings', 'SettingController');

Route::resource('email-templates', 'EmailTemplateController');

routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/redirect', 'SocialAuthFacebookController@redirect');
Route::get('/redirectgoogle', 'SocialAuthFacebookController@redirectToProvider');
Route::get('/callback', 'SocialAuthFacebookController@callback');
Route::get('/callbackgoogle', 'Auth\LoginController@handleProviderCallback');

app/Models/Notification.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

/**
 * @property integer id
 * @property integer sender_id
 * @property integer ref_id
 * @property string action_type
 * @property string url
 * @property string message
 * @property integer status
 * @property string created_at
 * @property string updated_at
 * @property string deleted_at
 *
 * @property User users
 *
 * @SWG\Definition(
 *      definition="Notification",
 *      required={"sender_id", "url", "action_type", "ref_id", "message", "status"},
 *      @SWG\Property(
 *          property="id",
 *          description="id",
 *          type="integer",
 *          format="int32"
 *      ),
 *      @SWG\Property(
 *          property="sender_id",
 *          description="sender_id",
 *          type="integer",
 *          format="int32"
 *      ),
 *      @SWG\Property(
 *          property="url",
 *          description="url",
 *          type="string"
 *      ),
 *      @SWG\Property(
 *          property="action_type",
 *          description="action_type",
 *          type="string"
 *      ),
 *      @SWG\Property(
 *          property="ref_id",
 *          description="ref_id",
 *          type="integer",
 *          format="int32"
 *      ),
 *      @SWG\Property(
 *          property="message",
 *          description="message",
 *          type="string"
 *      ),
 *      @SWG\Property(
 *          property="status",
 *          description="status",
 *          type="boolean"
 *      )
 * )
 */
class Notification extends Model
{
    use SoftDeletes;

    public $table = 'notifications';

    protected $dates = ['deleted_at'];

    public $fillable = [
        'sender_id',
        'url',
        'action_type',
        'ref_id',
        'message',
        'status'
    ];

    /**
     * The attributes that should be casted to native types.
     *
     * @var array
     */
    protected $casts = [
        'url'         => 'string',
        'action_type' => 'string',
        'message'     => 'string',
        'status'      => 'boolean'
    ];

    /**
     * The objects that should be append to toArray.
     *
     * @var array
     */
    protected $with = [];

    /**
     * The attributes that should be append to toArray.
     *
     * @var array
     */
    protected $appends = [];

    /**
     * The attributes that should be visible in toArray.
     *
     * @var array
     */
    protected $visible = [];

    /**
     * Validation create rules
     *
     * @var array
     */
    public static $rules = [
        'action_type' => 'required',
        'message'     => 'required',
    ];

    /**
     * Validation update rules
     *
     * @var array
     */
    public static $update_rules = [
        'action_type' => 'required',
        'message'     => 'required',
    ];

    /**
     * Validation api rules
     *
     * @var array
     */
    public static $api_rules = [
        'action_type' => 'required',
        'message'     => 'required'
    ];

    public function users()
    {
        return $this->belongsToMany(User::class, 'notification_users')->withPivot('status');
    }

    public function getUsersCsvAttribute()
    {
        return implode(",", $this->users->pluck('name')->all());
    }
}

app/Http/Controllers/Admin/NotificationController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Helper\BreadcrumbsRegister;
use App\DataTables\Admin\NotificationDataTable;
use App\Http\Requests\Admin;
use App\Http\Requests\Admin\CreateNotificationRequest;
use App\Http\Requests\Admin\UpdateNotificationRequest;
use App\Repositories\Admin\NotificationRepository;
use App\Repositories\Admin\UserRepository;
use App\Http\Controllers\AppBaseController;
use Illuminate\Http\Response;
use Illuminate\Support\Facades\Auth;
use Laracasts\Flash\Flash;

/**
 * Class NotificationController
 * @package App\Http\Controllers\Admin
 */
class NotificationController extends AppBaseController
{
    /** ModelName */
    private $ModelName;

    /** BreadCrumbName */
    private $BreadCrumbName;

    /** @var  NotificationRepository */
    private $notificationRepository;

    /** @var  UserRepository */
    private $userRepository;

    /**
     * NotificationController constructor.
     * @param NotificationRepository $notificationRepo
     * @param UserRepository $userRepo
     */
    public function __construct(NotificationRepository $notificationRepo, UserRepository $userRepo)
    {
        $this->notificationRepository = $notificationRepo;
        $this->userRepository = $userRepo;
        $this->ModelName = 'notifications';
        $this->BreadCrumbName = 'Notification';
    }

    /**
     * Display a listing of the Notification.
     *
     * @param NotificationDataTable $notificationDataTable
     * @return Response
     */
    public function index(NotificationDataTable $notificationDataTable)
    {
        BreadcrumbsRegister::Register($this->ModelName, $this->BreadCrumbName);
        return $notificationDataTable->render('admin.notifications.index');
    }

    /**
     * Show the form for creating a new Notification.
     *
     * @return Response
     */
    public function create()
    {
        $users = $this->userRepository->all()->pluck('name', 'id');
        BreadcrumbsRegister::Register($this->ModelName, $this->BreadCrumbName);
        return view('admin.notifications.create')->with('users', $users);
    }

    /**
     * Store a newly created Notification in storage.
     *
     * @param CreateNotificationRequest $request
     *
     * @return Response
     */
    public function store(CreateNotificationRequest $request)
    {
        $input = $request->all();
        $input['sender_id'] = Auth::id();

        $notification = $this->notificationRepository->create($input);
        $notification->users()->attach($input['send_to']);

        if (isset($input['push'])) {
            #Sent Push Notification

            $data['status'] = 1;
            $this->notificationRepository->update($data, $notification->id);
        }
        Flash::success('Notification saved successfully.');
        return redirect(route('admin.notifications.index'));
    }

    /**
     * Display the specified Notification.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function show($id)
    {
        $notification = $this->notificationRepository->findWithoutFail($id);

        if (empty($notification)) {
            Flash::error('Notification not found');

            return redirect(route('admin.notifications.index'));
        }

        BreadcrumbsRegister::Register($this->ModelName, $this->BreadCrumbName, $notification);
        return view('admin.notifications.show')->with('notification', $notification);
    }

    /**
     * Show the form for editing the specified Notification.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function edit($id)
    {
        $notification = $this->notificationRepository->findWithoutFail($id);

        if (empty($notification)) {
            Flash::error('Notification not found');

            return redirect(route('admin.notifications.index'));
        }

        if ($notification->status == 1) {
            Flash::error('Notification has been sent. Unable to be edited');

            return redirect(route('admin.notifications.index'));
        }
        $users = $this->userRepository->all()->pluck('name', 'id');

        BreadcrumbsRegister::Register($this->ModelName, $this->BreadCrumbName, $notification);
        return view('admin.notifications.edit')->with('notification', $notification)->with('users', $users);
    }

    /**
     * Update the specified Notification in storage.
     *
     * @param  int $id
     * @param UpdateNotificationRequest $request
     *
     * @return Response
     */
    public function update($id, UpdateNotificationRequest $request)
    {
        $notification = $this->notificationRepository->findWithoutFail($id);
        if (empty($notification)) {
            Flash::error('Notification not found');
            return redirect(route('admin.notifications.index'));
        }

        $notification = $this->notificationRepository->update($request->all(), $id);

        $existingMembers = $notification->users->pluck('id')->toArray();
        $selectedMembers = $request->send_to;
        $newMembers = array_diff($selectedMembers, $existingMembers);
        $membersToBeDeleted = array_diff($existingMembers, $selectedMembers);

        $notification->users()->attach($newMembers);
        $notification->users()->detach($membersToBeDeleted);

        if (isset($request->push)) {
            #Sent Push Notification

            $this->notificationRepository->update(['status' => 1], $id);
        }

        Flash::success('Notification updated successfully.');

        return redirect(route('admin.notifications.index'));
    }

    /**
     * Remove the specified Notification from storage.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function destroy($id)
    {
        $notification = $this->notificationRepository->findWithoutFail($id);

        if (empty($notification)) {
            Flash::error('Notification not found');

            return redirect(route('admin.notifications.index'));
        }

        $this->notificationRepository->delete($id);

        Flash::success('Notification deleted successfully.');
        return redirect(route('admin.notifications.index'));
    }
}

resources/views/admin/notifications/create.blade.php
@extends('admin.layouts.app')

@section('title')
    Notification
@endsection

@section('content')
    <div class="content">
        @include('adminlte-templates::common.errors')
        <div class="box box-primary">

            <div class="box-body">
                <div class="row">
                    {!! Form::open(['route' => 'admin.notifications.store']) !!}

                        @include('admin.notifications.fields')

                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/notifications/datatables_actions.blade.php
{!! Form::open(['route' => ['admin.notifications.destroy', $id], 'method' => 'delete']) !!}
<div class='btn-group'>
    @ability('super-admin' ,'notifications.show')
    <a href="{{ route('admin.notifications.show', $id) }}" class='btn btn-default btn-xs'>
        <i class="glyphicon glyphicon-eye-open"></i>
    </a>
    @endability
    @ability('super-admin' ,'notifications.edit')
    <a href="{{ route('admin.notifications.edit', $id) }}" class='btn btn-default btn-xs'>
        <i class="glyphicon glyphicon-edit"></i>
    </a>
    @endability
    @ability('super-admin' ,'notifications.destroy')
    {!! Form::button('<i class="glyphicon glyphicon-trash"></i>', [
        'type' => 'submit',
        'class' => 'btn btn-danger btn-xs',
        'onclick' => "confirmDelete($(this).parents('form')[0]); return false;"
    ]) !!}
    @endability
</div>
{!! Form::close() !!}

resources/views/admin/notifications/edit.blade.php
@extends('admin.layouts.app')

@section('title')
    {{ $notification->name }} <small>Notification</small>
@endsection

@section('content')
   <div class="content">
       @include('adminlte-templates::common.errors')
       <div class="box box-primary">
           <div class="box-body">
               <div class="row">
                   {!! Form::model($notification, ['route' => ['admin.notifications.update', $notification->id], 'method' => 'patch']) !!}

                        @include('admin.notifications.fields')

                   {!! Form::close() !!}
               </div>
           </div>
       </div>
   </div>
@endsection

resources/views/admin/notifications/fields.blade.php
<!-- Sender Id Field -->
<div class="form-group col-sm-6">
    {!! Form::label('sender_id', 'Send To:') !!}
    {!! Form::select('send_to[]', $users, isset($notification->users)?$notification->users:null, ['class' => 'form-control select2', 'multiple'=>'multiple']) !!}
</div>

<!-- Action Type Field -->
<div class="form-group col-sm-6">
    {!! Form::label('action_type', 'Action Type:') !!}
    {!! Form::select('action_type', ['android'=>'Android', 'IOS'=>'ios', 'both'=>'Both'], null, ['class' => 'form-control']) !!}
</div>

<!-- Ref Id Field -->
<div class="form-group col-sm-6">
    {!! Form::label('ref_id', 'Ref Id:') !!}
    {!! Form::number('ref_id', null, ['class' => 'form-control']) !!}
</div>

<!-- Message Field -->
<div class="form-group col-sm-12 col-lg-12">
    {!! Form::label('message', 'Message:') !!}
    {!! Form::textarea('message', null, ['class' => 'form-control']) !!}
</div>

<!-- Submit Field -->
<div class="form-group col-sm-12">
    {!! Form::submit('Save', ['class' => 'btn btn-primary']) !!}
    {!! Form::submit('Save & Sent', ['class' => 'btn btn-primary', 'name'=>'push']) !!}
    <a href="{!! route('admin.notifications.index') !!}" class="btn btn-default">Cancel</a>
</div>

resources/views/admin/notifications/index.blade.php
@extends('admin.layouts.app')

@section('title')
    Notifications
@endsection

@section('content')
    <div class="content">
        <div class="clearfix"></div>

        @include('flash::message')

        <div class="clearfix"></div>
        <div class="box box-primary">
            <div class="box-body">
                    @include('admin.notifications.table')
            </div>
        </div>
        <div class="text-center">
        
        </div>
    </div>
@endsection

resources/views/admin/notifications/show.blade.php
@extends('admin.layouts.app')

@section('title')
    Notification
@endsection

@section('content')
    <div class="content">
        <div class="box box-primary">
            <div class="box-body">
                <div class="row" style="padding-left: 20px">
                    <dl class="dl-horizontal">
                        @include('admin.notifications.show_fields')
                    </dl>
                    {!! Form::open(['route' => ['admin.notifications.destroy', $notification->id], 'method' => 'delete']) !!}
                    <div class='btn-group'>
                        @ability('super-admin' ,'notifications.show')
                        <a href="{!! route('admin.notifications.index') !!}" class="btn btn-default">
                            <i class="glyphicon glyphicon-arrow-left"></i> Back
                        </a>
                        @endability
                        @ability('super-admin' ,'notifications.edit')
                        <a href="{{ route('admin.notifications.edit', $notification->id) }}" class='btn btn-default'>
                            <i class="glyphicon glyphicon-edit"></i> Edit
                        </a>
                        @endability
                        @ability('super-admin' ,'notifications.destroy')
                        {!! Form::button('<i class="glyphicon glyphicon-trash"></i> Delete', [
                            'type' => 'submit',
                            'class' => 'btn btn-danger',
                            'onclick' => "confirmDelete($(this).parents('form')[0]); return false;"
                        ]) !!}
                        @endability
                    </div>
                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/notifications/show_fields.blade.php
<!-- Id Field -->
<dt>{!! Form::label('id', 'Id:') !!}</dt>
<dd>{!! $notification->id !!}</dd>

<!-- Sender Id Field -->
<dt>{!! Form::label('sender_id', 'Sender To:') !!}</dt>
<dd>{!! $notification->users_csv !!}</dd>

<!-- Url Field -->
<dt>{!! Form::label('url', 'Url:') !!}</dt>
<dd>{!! $notification->url !!}</dd>

<!-- Action Type Field -->
<dt>{!! Form::label('action_type', 'Action Type:') !!}</dt>
<dd>{!! $notification->action_type !!}</dd>

<!-- Ref Id Field -->
<dt>{!! Form::label('ref_id', 'Ref Id:') !!}</dt>
<dd>{!! $notification->ref_id !!}</dd>

<!-- Message Field -->
<dt>{!! Form::label('message', 'Message:') !!}</dt>
<dd>{!! $notification->message !!}</dd>

<!-- Status Field -->
<dt>{!! Form::label('status', 'Sent:') !!}</dt>
<dd>{!! $notification->status==0?'<span class="label label-danger">No</span>':'<span class="label label-success">Yes</span>' !!}</dd>

<!-- Created At Field -->
<dt>{!! Form::label('created_at', 'Created At:') !!}</dt>
<dd>{!! $notification->created_at !!}</dd>

<!-- Updated At Field -->
<dt>{!! Form::label('updated_at', 'Updated At:') !!}</dt>
<dd>{!! $notification->updated_at !!}</dd>

resources/views/admin/notifications/table.blade.php
@push('css')
    @include('admin.layouts.datatables_css')
@endpush

{!! $dataTable->table(['width' => '100%']) !!}

@push('scripts')
    @include('admin.layouts.datatables_js')
    {!! $dataTable->scripts() !!}
@endpush