routes/admin.php
<?php


Auth::routes();

Route::get('/', 'HomeController@index')->name('dashboard');
Route::get('/home', 'HomeController@index')->name('dashboard');
Route::get('/dashboard', 'HomeController@index')->name('dashboard');
Route::get('about', 'HomeController@index');

Route::resource('roles', 'RoleController');

Route::resource('modules', 'ModuleController');

Route::get('/module/step1/{id?}', 'ModuleController@getStep1')->name('modules.create');
Route::get('/module/step2/{tablename?}', 'ModuleController@getStep2')->name('modules.create');
Route::get('/getJoinFields/{tablename?}', 'ModuleController@getJoinFields');
Route::get('/module/step3/{tablename?}', 'ModuleController@getStep3')->name('modules.create');

Route::post('/step1', 'ModuleController@postStep1');
Route::post('/step2', 'ModuleController@postStep2');
Route::post('/step3', 'ModuleController@postStep3');


Route::resource('users', 'UserController');

Route::resource('permissions', 'PermissionController');

//Route::resource('profile', 'UserController');

Route::get('user/profile', 'UserController@profile')->name('users.profile');
//Route::patch('users/profile-update/{id}', 'UserController@profileUpdate')->name('users.profile-update');

Route::resource('languages', 'LanguageController');

Route::resource('pages', 'PageController');

Route::resource('contactus', 'ContactUsController');

Route::resource('notifications', 'NotificationController');

Route::resource('menus', 'MenuController');

//Menu #TODO need to be fixed
Route::get('statusChange/{id}', 'MenuController@statusChange');

Route::post('updateChannelPosition', 'MenuController@update_channel_position')->name('channels');
Route::resource('settings', 'SettingController');

Route::resource('email-templates', 'EmailTemplateController');

routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/redirect', 'SocialAuthFacebookController@redirect');
Route::get('/redirectgoogle', 'SocialAuthFacebookController@redirectToProvider');
Route::get('/callback', 'SocialAuthFacebookController@callback');
Route::get('/callbackgoogle', 'Auth\LoginController@handleProviderCallback');

app/Models/EmailTemplate.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

/**
 * @property integer id
 * @property string name
 * @property string created_at
 * @property string updated_at
 * @property string deleted_at
 *
 * @SWG\Definition(
 *      definition="EmailTemplate",
 *      required={"key", "html_body", "text_body"},
 *      @SWG\Property(
 *          property="id",
 *          description="id",
 *          type="integer",
 *          format="int32"
 *      ),
 *      @SWG\Property(
 *          property="key",
 *          description="key",
 *          type="string"
 *      ),
 *      @SWG\Property(
 *          property="html_body",
 *          description="html_body",
 *          type="string"
 *      ),
 *      @SWG\Property(
 *          property="text_body",
 *          description="text_body",
 *          type="string"
 *      ),
 *      @SWG\Property(
 *          property="created_at",
 *          description="created_at",
 *          type="string",
 *          format="date-time"
 *      ),
 *      @SWG\Property(
 *          property="updated_at",
 *          description="updated_at",
 *          type="string",
 *          format="date-time"
 *      ),
 *      @SWG\Property(
 *          property="deleted_at",
 *          description="deleted_at",
 *          type="string",
 *          format="date-time"
 *      )
 * )
 */
class EmailTemplate extends Model
{
    use SoftDeletes;

    public $table = 'email_templates';
    

    protected $dates = ['deleted_at'];


    public $fillable = [
        'key',
        'html_body',
        'text_body'
    ];

    /**
     * The attributes that should be casted to native types.
     *
     * @var array
     */
    protected $casts = [
        'id' => 'integer',
        'key' => 'string',
        'html_body' => 'string',
        'text_body' => 'string'
    ];

    /**
     * The objects that should be append to toArray.
     *
     * @var array
     */
     protected $with = [];

    /**
     * The attributes that should be append to toArray.
     *
     * @var array
     */
    protected $appends = [];

    /**
     * The attributes that should be visible in toArray.
     *
     * @var array
     */
    protected $visible = [];

    /**
     * Validation create rules
     *
     * @var array
     */
    public static $rules = [
        'key' => 'required',
        'html_body' => 'required',
        'text_body' => 'required'
    ];

    /**
     * Validation update rules
     *
     * @var array
     */
    public static $update_rules = [
        'key' => 'required',
        'html_body' => 'required',
        'text_body' => 'required'
    ];

    /**
     * Validation api rules
     *
     * @var array
     */
    public static $api_rules = [
        'key' => 'required',
        'html_body' => 'required',
        'text_body' => 'required'
    ];
	
	/**
     * Validation api update rules
     *
     * @var array
     */
    public static $api_update_rules = [
        'key' => 'required',
        'html_body' => 'required',
        'text_body' => 'required'
    ];

    
}

app/Http/Controllers/Admin/EmailTemplateController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Helper\BreadcrumbsRegister;
use App\DataTables\Admin\EmailTemplateDataTable;
use App\Http\Requests\Admin;
use App\Http\Requests\Admin\CreateEmailTemplateRequest;
use App\Http\Requests\Admin\UpdateEmailTemplateRequest;
use App\Repositories\Admin\EmailTemplateRepository;
use App\Http\Controllers\AppBaseController;
use Laracasts\Flash\Flash;
use Illuminate\Http\Response;

class EmailTemplateController extends AppBaseController
{
    /** ModelName */
    private $ModelName;

    /** BreadCrumbName */
    private $BreadCrumbName;

    /** @var  EmailTemplateRepository */
    private $emailTemplateRepository;

    public function __construct(EmailTemplateRepository $emailTemplateRepo)
    {
        $this->emailTemplateRepository = $emailTemplateRepo;
        $this->ModelName = 'email-templates';
        $this->BreadCrumbName = 'Email Templates';
    }

    /**
     * Display a listing of the EmailTemplate.
     *
     * @param EmailTemplateDataTable $emailTemplateDataTable
     * @return Response
     */
    public function index(EmailTemplateDataTable $emailTemplateDataTable)
    {
        BreadcrumbsRegister::Register($this->ModelName,$this->BreadCrumbName);
        return $emailTemplateDataTable->render('admin.email_templates.index', ['title' => $this->BreadCrumbName]);
    }

    /**
     * Show the form for creating a new EmailTemplate.
     *
     * @return Response
     */
    public function create()
    {
        BreadcrumbsRegister::Register($this->ModelName,$this->BreadCrumbName);
        return view('admin.email_templates.create')->with(['title' => $this->BreadCrumbName]);
    }

    /**
     * Store a newly created EmailTemplate in storage.
     *
     * @param CreateEmailTemplateRequest $request
     *
     * @return Response
     */
    public function store(CreateEmailTemplateRequest $request)
    {
        $emailTemplate = $this->emailTemplateRepository->saveRecord($request);

        Flash::success($this->BreadCrumbName . ' saved successfully.');
        if (isset($request->continue)) {
            $redirect_to = redirect(route('admin.email-templates.create'));
        } elseif (isset($request->translation)) {
            $redirect_to = redirect(route('admin.email-templates.edit', $emailTemplate->id));
        } else {
            $redirect_to = redirect(route('admin.email-templates.index'));
        }
        return $redirect_to->with([
            'title' => $this->BreadCrumbName
        ]);
    }

    /**
     * Display the specified EmailTemplate.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function show($id)
    {
        $emailTemplate = $this->emailTemplateRepository->findWithoutFail($id);

        if (empty($emailTemplate)) {
            Flash::error($this->BreadCrumbName . ' not found');
            return redirect(route('admin.email-templates.index'));
        }

        BreadcrumbsRegister::Register($this->ModelName,$this->BreadCrumbName, $emailTemplate);
        return view('admin.email_templates.show')->with(['emailTemplate' => $emailTemplate, 'title' => $this->BreadCrumbName]);
    }

    /**
     * Show the form for editing the specified EmailTemplate.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function edit($id)
    {
        $emailTemplate = $this->emailTemplateRepository->findWithoutFail($id);

        if (empty($emailTemplate)) {
            Flash::error($this->BreadCrumbName . ' not found');
            return redirect(route('admin.email-templates.index'));
        }

        BreadcrumbsRegister::Register($this->ModelName,$this->BreadCrumbName, $emailTemplate);
        return view('admin.email_templates.edit')->with(['emailTemplate' => $emailTemplate, 'title' => $this->BreadCrumbName]);
    }

    /**
     * Update the specified EmailTemplate in storage.
     *
     * @param  int              $id
     * @param UpdateEmailTemplateRequest $request
     *
     * @return Response
     */
    public function update($id, UpdateEmailTemplateRequest $request)
    {
        $emailTemplate = $this->emailTemplateRepository->findWithoutFail($id);

        if (empty($emailTemplate)) {
            Flash::error($this->BreadCrumbName . ' not found');
            return redirect(route('admin.email-templates.index'));
        }

        $emailTemplate = $this->emailTemplateRepository->updateRecord($request, $emailTemplate);

        Flash::success($this->BreadCrumbName . ' updated successfully.');
        if (isset($request->continue)) {
            $redirect_to = redirect(route('admin.email-templates.create'));
        } else {
            $redirect_to = redirect(route('admin.email-templates.index'));
        }
        return $redirect_to->with(['title' => $this->BreadCrumbName]);
    }

    /**
     * Remove the specified EmailTemplate from storage.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function destroy($id)
    {
        $emailTemplate = $this->emailTemplateRepository->findWithoutFail($id);

        if (empty($emailTemplate)) {
            Flash::error($this->BreadCrumbName . ' not found');
            return redirect(route('admin.email-templates.index'));
        }

        $this->emailTemplateRepository->deleteRecord($id);

        Flash::success($this->BreadCrumbName . ' deleted successfully.');
        return redirect(route('admin.email-templates.index'))->with(['title' => $this->BreadCrumbName]);
    }
}

resources/views/admin/email_templates/create.blade.php
@extends('admin.layouts.app')

@section('title')
    {{ $title }}
@endsection

@section('content')
    <div class="content">
        @include('adminlte-templates::common.errors')
        <div class="box box-primary">

            <div class="box-body">
                <div class="row">
                    {!! Form::open(['route' => 'admin.email-templates.store', 'files' => true]) !!}

                        @include('admin.email_templates.fields')

                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/email_templates/datatables_actions.blade.php
{!! Form::open(['route' => ['admin.email-templates.destroy', $id], 'method' => 'delete']) !!}
<div class='btn-group'>
    @ability('super-admin' ,'email-templates.show')
    <a href="{{ route('admin.email-templates.show', $id) }}" class='btn btn-default btn-xs'>
        <i class="glyphicon glyphicon-eye-open"></i>
    </a>
    @endability
    @ability('super-admin' ,'email-templates.edit')
    <a href="{{ route('admin.email-templates.edit', $id) }}" class='btn btn-default btn-xs'>
        <i class="glyphicon glyphicon-edit"></i>
    </a>
    @endability
    @ability('super-admin' ,'email-templates.destroy')
    {!! Form::button('<i class="glyphicon glyphicon-trash"></i>', [
        'type' => 'submit',
        'class' => 'btn btn-danger btn-xs',
        'onclick' => "confirmDelete($(this).parents('form')[0]); return false;"
    ]) !!}
    @endability
</div>
{!! Form::close() !!}

resources/views/admin/email_templates/edit.blade.php
@extends('admin.layouts.app')

@section('title')
    {{ $emailTemplate->name }} <small>{{ $title }}</small>
@endsection

@section('content')
   <div class="content">
       @include('adminlte-templates::common.errors')
       <div class="box box-primary">
           <div class="box-body">
               <div class="row">
                   {!! Form::model($emailTemplate, ['route' => ['admin.email-templates.update', $emailTemplate->id], 'method' => 'patch', 'files' => true]) !!}

                        @include('admin.email_templates.fields')

                   {!! Form::close() !!}
               </div>
           </div>
       </div>
   </div>
@endsection

resources/views/admin/email_templates/fields.blade.php
<!-- Key Field -->
<div class="form-group col-sm-6">
    {!! Form::label('key', 'Key:') !!}
    {!! Form::text('key', null, ['class' => 'form-control', 'placeholder'=>'Enter key']) !!}
</div>

<!-- Html Body Field -->
<div class="form-group col-sm-6">
    {!! Form::label('html_body', 'Html Body:') !!}
    {!! Form::text('html_body', null, ['class' => 'form-control', 'placeholder'=>'Enter html_body']) !!}
</div>

<!-- Text Body Field -->
<div class="form-group col-sm-6">
    {!! Form::label('text_body', 'Text Body:') !!}
    {!! Form::text('text_body', null, ['class' => 'form-control', 'placeholder'=>'Enter text_body']) !!}
</div>

<!-- Submit Field -->
<div class="form-group col-sm-12">
    {!! Form::submit('Save', ['class' => 'btn btn-primary']) !!}
    @if(!isset($emailTemplate))
        {!! Form::submit(__('Save And Add Translations'), ['class' => 'btn btn-primary', 'name'=>'translation']) !!}
    @endif
    {!! Form::submit(__('Save And Add More'), ['class' => 'btn btn-primary', 'name'=>'continue']) !!}
    <a href="{!! route('admin.email-templates.index') !!}" class="btn btn-default">Cancel</a>
</div>

resources/views/admin/email_templates/index.blade.php
@extends('admin.layouts.app')

@section('title')
    {{ $title }}
@endsection

@section('content')
    <div class="content">
        <div class="clearfix"></div>

        @include('flash::message')

        <div class="clearfix"></div>
        <div class="box box-primary">
            <div class="box-body">
                    @include('admin.email_templates.table')
            </div>
        </div>
        <div class="text-center">
        
        </div>
    </div>
@endsection

resources/views/admin/email_templates/show.blade.php
@extends('admin.layouts.app')

@section('title')
    {{ $title }}
@endsection

@section('content')
    <div class="content">
        <div class="box box-primary">
            <div class="box-body">
                <div class="row" style="padding-left: 20px">
                    <dl class="dl-horizontal">
                        @include('admin.email_templates.show_fields')
                    </dl>
                    {!! Form::open(['route' => ['admin.email-templates.destroy', $emailTemplate->id], 'method' => 'delete']) !!}
                    <div class='btn-group'>
                        @ability('super-admin' ,'email-templates.show')
                        <a href="{!! route('admin.email-templates.index') !!}" class="btn btn-default">
                            <i class="glyphicon glyphicon-arrow-left"></i> Back
                        </a>
                        @endability
                    </div>
                    <div class='btn-group'>
                        @ability('super-admin' ,'email-templates.edit')
                        <a href="{{ route('admin.email-templates.edit', $emailTemplate->id) }}" class='btn btn-default'>
                            <i class="glyphicon glyphicon-edit"></i> Edit
                        </a>
                        @endability
                    </div>
                    <div class='btn-group'>
                        @ability('super-admin' ,'email-templates.destroy')
                        {!! Form::button('<i class="glyphicon glyphicon-trash"></i> Delete', [
                            'type' => 'submit',
                            'class' => 'btn btn-danger',
                            'onclick' => "confirmDelete($(this).parents('form')[0]); return false;"
                        ]) !!}
                        @endability
                    </div>
                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/email_templates/show_fields.blade.php
<!-- Id Field -->
<dt>{!! Form::label('id', 'Id:') !!}</dt>
<dd>{!! $emailTemplate->id !!}</dd>

<!-- Key Field -->
<dt>{!! Form::label('key', 'Key:') !!}</dt>
<dd>{!! $emailTemplate->key !!}</dd>

<!-- Html Body Field -->
<dt>{!! Form::label('html_body', 'Html Body:') !!}</dt>
<dd>{!! $emailTemplate->html_body !!}</dd>

<!-- Text Body Field -->
<dt>{!! Form::label('text_body', 'Text Body:') !!}</dt>
<dd>{!! $emailTemplate->text_body !!}</dd>

<!-- Created At Field -->
<dt>{!! Form::label('created_at', 'Created At:') !!}</dt>
<dd>{!! $emailTemplate->created_at !!}</dd>

<!-- Updated At Field -->
<dt>{!! Form::label('updated_at', 'Updated At:') !!}</dt>
<dd>{!! $emailTemplate->updated_at !!}</dd>

<!-- Deleted At Field -->
<dt>{!! Form::label('deleted_at', 'Deleted At:') !!}</dt>
<dd>{!! $emailTemplate->deleted_at !!}</dd>

resources/views/admin/email_templates/table.blade.php
@push('css')
    @include('admin.layouts.datatables_css')
@endpush

{!! $dataTable->table(['width' => '100%']) !!}

@push('scripts')
    @include('admin.layouts.datatables_js')
    {!! $dataTable->scripts() !!}
@endpush